Document: dropwizard-scala-sample
Title: Debian dropwizard-scala-sample Manual
Author: <insert document author here>
Abstract: This manual describes what dropwizard-scala-sample is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dropwizard-scala-sample/dropwizard-scala-sample.sgml.gz

Format: postscript
Files: /usr/share/doc/dropwizard-scala-sample/dropwizard-scala-sample.ps.gz

Format: text
Files: /usr/share/doc/dropwizard-scala-sample/dropwizard-scala-sample.text.gz

Format: HTML
Index: /usr/share/doc/dropwizard-scala-sample/html/index.html
Files: /usr/share/doc/dropwizard-scala-sample/html/*.html
